# ~/.config/hypr/Input.conf



#################################
###   ___                _    ###
###  |_ _|_ _  _ __ _  _| |_  ###
###  | || ' \| '_ \ || |  _|  ###
###  |___|_||_| .__/\_,_|\__| ### 
###           |_|             ###
################################# 


input {
    kb_layout = de
    kb_options = caps:escape
    accel_profile = flat
    follow_mouse = 1
    sensitivity = 0.3
    force_no_accel = true
}


device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


#Ich beschreib dir schonmal wie es geht, dann kannst du es schonmal versuchen. Also du l
