# ~/.config/hypr/windows.conf 



#############################################################################################################
###  __      __       _                           _  __      ___         _                     _          ###
###  \ \    / /__ _ _| |__ ____ __  __ _ __ ___  | | \ \    / (_)_ _  __| |_____ __ ___ _ _  _| |___ ___  ###
###   \ \/\/ / _ \ '_| / /(_-< '_ \/ _` / _/ -_) | |  \ \/\/ /| | ' \/ _` / _ \ V  V / '_| || | / -_|_-<  ###
###    \_/\_/\___/_| |_\_\/__/ .__/\__,_\__\___| | |   \_/\_/ |_|_||_\__,_\___/\_/\_/|_|  \_,_|_\___/__/  ###
###                          |_|                 |_|                                                      ###
#############################################################################################################


 exec-once = /home/azu/.config/hypr/scripts/start.sh
 exec-once = /home/azu/.config/hypr/scripts/kitty.sh
 exec-once = qs & 

 workspace =1, monitor:DP-2 
 workspace =3, monitor:DP-2 
 workspace =5, monitor:DP-2 
 workspace =7, monitor:DP-2
 workspace =9, monitor:DP-2

 workspace =2,  monitor:DP-1 
 workspace =4,  monitor:DP-1
 workspace =6,  monitor:DP-1
 workspace =8,  monitor:DP-1
 workspace =10, monitor:DP-1

 windowrule = workspace 1, match:class kitty 
 windowrule = workspace 2, match:class zen	
 windowrule = workspace 4, match:class discord
 windowrule = workspace 5, match:class steam
 windowrule = workspace 6, match:class com.obsproject.Studio
 windowrule = workspace 6, match:class org.openrgb.OpenRGB
 windowrule = workspace 3, match:title tmux_nvim
 windowrule = workspace 3, match:class nvim-reload

 windowrule = fullscreen 1, match:class gamescope
 windowrule = fullscreen 1, match:class steam_app_\d+
 windowrule = workspace 7 silent,match:class gamescope
 windowrule = workspace 7 silent,match:class steam_app_\d+
 windowrule = no_blur on,match:class steam_app_\d+
 workspace = 7, border:false, rounding:false
 windowrule = match:class ^(org.quickshell)$, float on, center on, size 400 500, border_size 0, no_shadow on, rounding 0
 windowrule = match:title ^(music_picker)$, float on, center on, size 1000 600, border_size 0, no_shadow on, rounding 0
 windowrule = match:title ^(wallpaper-picker)$, float on, center on, size 1264 720, border_size 0, no_shadow on, rounding 0
 windowrule = match:class ^fzfwindows$, float true, size 900 600, center true
 windowrule = match:class ^swayimg$, float true, size 1600 1200, center true
 windowrule = match:class ^mpv$, float true, size 1600 1200, center true

 windowrule = suppress_event maximize, match:class .*
 windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
 
 windowrule {
    name = zen-opacity
    match:class = ^(zen)$
    opaque = on
 }


