#-----------------# AZU #-----------------#

music_directory "/home/azu/Music"
playlist_directory "/home/azu/Music"

auto_update "yes"
restore_paused "yes"

audio_output {
	type "pulse"
	name "pulse"
}
