$text_color             = rgba({color7.strip}ff)
$entry_color            = rgba({color7.strip}ff)
$entry_border_color     = rgba({color4.strip}ff)
$entry_background_color = rgba({color0.strip}cc)
$check_color            = rgba({color2.strip}ff)
$fail_color             = rgba({color1.strip}ff)
$capslock_color         = rgba({color3.strip}ff)

$font_family            = JetBrainsMono Nerd Font
$font_family_clock      = JetBrainsMono Nerd Font
